### ISSUE TITLE
Stop is not working as intended when combining react and hook

### ISSUE THREAD

**Issue by Leekao** [samhirtarif/react-audio-recorder#17]
I tried to combine the hooks with the react element and it is not working, when I use `startRecording()` it begins to record but running the `stopRecording()` does not call the `onComplete` function I added, pressing the stop button myself on the UI does call it, also I see the record icon on the tab and on my windows bar even after the recording stopped.

I'm using the latest version of the project.

**Comment by Leekao** [comment]
Yes, I'm using 1.0.4, I'm sorry but I do not have a snippet, I altered my code and got it to work without the react element, sorry, I'll close this issue for now.

**Comment by samhirtarif** [comment]
Just a heads up, I noticed you wrote `onComplete` in your original comment, whereas the method you want to get called on recording completion is supposed to be assigned to `onRecordingComplete`
