### ISSUE TITLE
hook get onRecordingComplete

### ISSUE THREAD

**Issue by jeriferdiano** [samhirtarif/react-audio-recorder#18]
how to get blob file if i just use hook? because in hook there is no onRecordingComplete

**Comment by samhirtarif** [comment]
@jeriferdiano - The hook provides `recordingBlob` which would have the blob file after the `stopRecording` method from the hook has been called.

**Comment by jeriferdiano** [comment]
@samhirtarif 
but after calling stoprecording recordingBlob it's still undefined

**Comment by samhirtarif** [comment]
Would it be possible for you to share a code snippet? I would be able to help better that way.

**Comment by samhirtarif** [comment]
I believe it should be `recorder.stopRecording()` in the `else` block.

**Comment by jeriferdiano** [comment]
> I believe it should be `recorder.stopRecording()` in the `else` block.

![image](https://user-images.githubusercontent.com/54654225/206126374-96ba5832-364f-429d-b768-080dd16d1f73.png)
sorry I was wrong, but I have changed it still can't recordingBlob

**Comment by samhirtarif** [comment]
That is expected too I believe. It should be accessible on next render (because of state changes)
Could you try something adding something along these lines to your component
```js
useEffect(() => {
    if (recorder.recordingBlob) {
        console.log(recorder.recordingBlob)
    }
}, [recorder.recordingBlob])
```
