### ISSUE TITLE
NextJs - "vite-plugin-css-injected-by-js ReferenceError: document is not defined"

### ISSUE THREAD

**Issue by Lecha91** [samhirtarif/react-audio-recorder#23]
Hello,

In NextJs, when I'm starting the development mode, I get the following error in the terminal:
"vite-plugin-css-injected-by-js ReferenceError: document is not defined".

Everything works fine, but this error is present in the terminal.

I am using the latest version of the package.

**Comment by samhirtarif** [comment]
@Lecha91 - sorry, I've been busy lately, I'll try and take a look at this in the upcoming week.
Would it be possible for you to spin up a bare minimum piece of code that gives this error on [stackblitz](https://stackblitz.com/)?
Would really appreciate that

**Comment by samhirtarif** [comment]
The error has been resolved in this [PR](https://github.com/samhirtarif/react-audio-recorder/pull/26)
