### ISSUE TITLE
the blob does not gets discarded when the "discard recording" button is clicked, it behaves same as "save recording" button

### ISSUE THREAD

**Issue by usamaadev** [samhirtarif/react-audio-recorder#24]
Hello there,

While experiencing the react-audio-voice-recorder, when the user clicks to discard the recorded audio, it behaves same as if save recording button is clicked.

**Comment by samhirtarif** [comment]
@usamaadev I am unable to reproduce this one. Would it be possible to share your code or perhaps share the scenario in more detail?

**Comment by samhirtarif** [comment]
Marking this issue as closed since it has not been reproducible. Can be re-opened when further details are provided.
