### ISSUE TITLE
recordingBlob undefined

### ISSUE THREAD

**Issue by TyposBro** [samhirtarif/react-audio-recorder#27]
Hi there.
I wanted to use this library's hooks but can't access to recordingBlob.

Hook usage
const {
    startRecording,
    stopRecording,
    togglePauseResume,
    recordingBlob,
    isRecording,
    isPaused,
    recordingTime,
  } = useAudioRecorder();
  
  
  const handleSave = () => {
    stopRecording();
    setBlob(recordingBlob);
  };

** Usage: user can toggle pause/resume as much as they want. But once they press pause button, save button will appear and they can either save or discard it. Save button is implemented by handleSave function

**Comment by samhirtarif** [comment]
Hey @TyposBro - I believe doing something like this may solve your problem
```js
useEffect(() => {
   if (!recordingBlob) return;

   setBlob(recordingBlob)
}, [recordingBlob])

const handleSave = () => {
    stopRecording();
};
```

Let me know if this helps

**Comment by TyposBro** [comment]
Yeah, works. Sorry for my silly issue🥹
