### ISSUE TITLE
is Recording possible in another format other than weba format?

### ISSUE THREAD

**Issue by dinakar17** [samhirtarif/react-audio-recorder#29]
Currently, I know when the recording is done the audio is rendered in '.weba' format. I was wondering whether it is possible to render it in another format.

**Comment by chiangs** [comment]
it comes as .webm for me but you can also rename it to .opus

**Comment by samhirtarif** [comment]
This is something I'll have to look into.
However, I am marking this as closed, since it doesn't constitute as an issue.

**Comment by samhirtarif** [comment]
@dinakar17 - Two new props have been added that determine whether an audio recording should be downloaded and what format should be used.
You can checkout out [here](https://stackblitz.com/edit/react-ts-cc5l47?file=App.tsx) for how it works
