### ISSUE TITLE
No audio recorded in iOS Safari.

### ISSUE THREAD

**Issue by harshtopica** [samhirtarif/react-audio-recorder#30]
I've tried the example from the Readme also.
https://stackblitz.com/edit/react-ts-ryj6jz?file=App.tsx

But it doesn't record anything.
is this an issue, or there is just no support?

**Comment by samhirtarif** [comment]
@harshtopica - I tried the stackblitz example on iOS safari (iOS version 16.0 (20A362)) and it worked as expected. Could you share more details?

**Comment by harshtopica** [comment]
Yeah, actually I tried on simulator earlier and it didn't seem to work.
Now, I've tried in the actual device and it's working fine. 💯
