### ISSUE TITLE
upload blob to server

### ISSUE THREAD

**Issue by gukii** [samhirtarif/react-audio-recorder#39]
any idea on how best to upload the created blob to a node server or s3 in mp3 format?
directly send the blob, or use the hook's download function first?

**Comment by samhirtarif** [comment]
You won't need to download the file first, that's for sure. You can [upload the blob](https://www.geeksforgeeks.org/how-can-javascript-upload-a-blob/) file to the server and then upload it to s3 if needed using the [S3 class](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html) from [aws-sdk](https://www.npmjs.com/package/aws-sdk).

The reason I'd recommend not uploading directly to s3 from the frontend is that you risk exposing your AWS access key and secret (unless [done properly](https://docs.aws.amazon.com/AmazonS3/latest/userguide/PresignedUrlUploadObject.html))

PS: I am marking this issue as closed, but feel free to continue the discussion
