### ISSUE TITLE
Ability to configure MediaTrackConstraints

### ISSUE THREAD

**Issue by Arisstath** [samhirtarif/react-audio-recorder#44]
Hello, great job on the package.

For our use case, we require lower level access to the parameters of getUserMedia(), specifically
https://github.com/samhirtarif/react-audio-recorder/blob/edc8208b335db35103d88378db59760d15fec5eb/src/hooks/useAudioRecorder.ts#L52-L54

We would like the ability to do something like that
```
navigator.mediaDevices
      .getUserMedia({ audio: {
          echoCancellation: false,
          noiseSuppression: false,
        }
      }
```

**Comment by samhirtarif** [comment]
@Arisstath - I've added the ability to pass these constraints to both the [`AudioRecorder`](https://stackblitz.com/edit/react-ts-cc5l47?file=App.tsx) component and the [`useAudioRecorder`](https://stackblitz.com/edit/react-ts-ryj6jz?file=App.tsx) hook. 
Note: In case you are using both the hook and the component in combination, the constraints need to be passed to the hook.

Also, please support the repo by leaving a ⭐ . Thanks!
