### ISSUE TITLE
Callback if recording  permission is denied

### ISSUE THREAD

**Issue by adriandiaz** [samhirtarif/react-audio-recorder#46]
Is there a callback if recording permission is denied or disabled by default (e.g. chrome app on an iphone)? Would be nice to signal to the user to enable microphone permission

**Comment by samhirtarif** [comment]
@adriandiaz - The following feature has been adding this [PR](https://github.com/samhirtarif/react-audio-recorder/pull/47).

You can follow the example [here](https://stackblitz.com/edit/react-ts-cc5l47?file=App.tsx) or [here](https://stackblitz.com/edit/react-ts-ryj6jz?file=App.tsx) on how to use this.

Would really appreciate it if you could support the repo by leaving a ⭐

**Comment by adriandiaz** [comment]
@samhirtarif thanks so much for being so responsive - you are awesome! ⭐ definitely earned!
