### ISSUE TITLE
Build prod issue

### ISSUE THREAD

**Issue by duytk7** [samhirtarif/react-audio-recorder#52]
**Encountered this issue when build prod**

[0mFailed to compile.

./node_modules/react-audio-voice-recorder/dist/react-audio-visualize.es.0ccda538.mjs
Can't import the named export 'useCallback' from non EcmaScript module (only default export is available)

[91merror Command failed with exit code 1.
[0minfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command '/bin/sh -c yarn build-prod' returned a non-zero code: 1

**Comment by samhirtarif** [comment]
@duytk7 - Could you share which build tool and bundler you're using?

**Comment by samhirtarif** [comment]
I was only able to reproduce this with a CRA bootstrapped project and that too was fixed by updating `react-scripts` as mentioned in [this thread](https://github.com/facebook/react/issues/26691#issuecomment-1520589570) on [facebook/react](https://github.com/facebook/react)
