### ISSUE TITLE
Firefox - error

### ISSUE THREAD

**Issue by HarisHodzicnt** [samhirtarif/react-audio-recorder#53]
If we try to use library in Firefox, error will occur. 
When showVisualizer is set to true.
Current "fix" for anyone that are using showVisualizer, you can add 
showVisualizer={!navigator.userAgent.includes("Firefox")}, 
in order to "fix" error in the browser until proper fix takes a place.

**Comment by samhirtarif** [comment]
@HarisHodzicnt - Could you also please mention the OS you were using?

**Comment by samhirtarif** [comment]
Fixed with PR #59
