### ISSUE TITLE
Recorded webm files don't trigger a "stop" when played

### ISSUE THREAD

**Issue by theDanielJLewis** [samhirtarif/react-audio-recorder#58]
Here's a weird issue! 

I'm using only the recording part of this module, and then I use your audio player both immediately after recording and on a separate page where the recordings are loaded from their storage.

The problem I've noticed is that the .webm (or renamed to .opus) files recorded with this module do not trigger a "stop" when fully played in your player.

I've tried other .webm files and they work fine, but all the .webm files from this recorder keep the player in a "playing" state even though the audio has ended.

The play/pause button remains paused and you have to click it _twice_ before playback can start over.

I've used the player code exactly from the examples and it works fine when I use your demo audio file. But if I change only the `src` to one recorded with this audio recorder, that file has a problem.

Here's a file you can try yourself for testing:

https://www.dropbox.com/s/50ynqgkn0kc9p70/recorded-test.webm?dl=1

**Comment by theDanielJLewis** [comment]
Interestingly, the player's `onended` _does_ get called when the audio finishes playing.

But why do only these webm files cause it to then just sit there and do nothing after playback ends?

**Comment by samhirtarif** [comment]
I believe this could be because the audio field recorded through the media recorder gets a `duration` of `Infinity`
I'll provide a quick fix for this this in the [react-audio-player-component](https://www.npmjs.com/package/react-audio-player-component) today. And look at this in-depth on how to fix the `Infinity` duration over the weekend

**Comment by samhirtarif** [comment]
I have updated [react-audio-player-component](https://www.npmjs.com/package/react-audio-player-component) to handle this properly for now, just update the package to the latest version.

And as for this issue, a little research show that the `duration` may be problematic for the `webm` format, but I'll certainly have to dig deeper.

**Comment by theDanielJLewis** [comment]
Awesome. Thank you!

**Comment by samhirtarif** [comment]
This is a [known issue](https://bugs.chromium.org/p/chromium/issues/detail?id=642012).
Can be side-stepped using packages like [`webm-duration-fix`](https://www.npmjs.com/package/webm-duration-fix)
Files downloaded with use of FFmpeg when [cross-origin isolation](https://web.dev/cross-origin-isolation-guide/) is enabled for the site would also have this problem resolved
