### ISSUE TITLE
Error on Safari

### ISSUE THREAD

**Issue by timhc22** [samhirtarif/react-audio-recorder#61]
u.roundRect is not a function. (In 'u.roundRect(a,c,f,l,50)', 'u.roundRect' is undefined)

I'm getting this error on Safari when trying to use the record feature (which crashes the whole browser). Happy to provide more details if needed, unfortunately can't seem to see what is causing it..

**Comment by samhirtarif** [comment]
More details would certainly help. I've tried on safari on mac and iOS and did not get this error (with `showVisualizer` set to `true` as well)
I believe you would have the `showVisualizer` option set to `true`. Since the visualizer is what uses the `roundRect` method.

**Comment by timhc22** [comment]
`
        <AudioRecorder
          onRecordingComplete={(blob) => addAudioElement(blob)}
          recorderControls={recorderControls}
          audioTrackConstraints={{
            noiseSuppression: true,
            echoCancellation: true,
          }}
          showVisualizer={true}
          // downloadOnSavePress={true}
          downloadFileExtension="mp3"
        />`

This is the exact config I am using in React ^

**Comment by timhc22** [comment]
I think it is the show visualiser for me, because it works when I comment out that line

**Comment by samhirtarif** [comment]
Could you share the OS and the version of safari you're using? Also the version of the npm package?

**Comment by timhc22** [comment]
mac os Monterrey 12.3.1
Safari: Version 15.4 (17613.1.17.1.13)
"react-audio-voice-recorder": "^2.0.0",

Also, on a slightly separate note (happy to open a new discussion), do you know what format the file is in Safari? I am sending the buffer to my backend, but it is not webm format, I guess it will be ACC or something?

**Comment by samhirtarif** [comment]
It turns out to have the mime type `application/octet-stream;`

**Comment by timhc22** [comment]
Interesting, I think Chrome on iOS might be the same because of the way it is implemented:

https://news.ycombinator.com/item?id=25850091#:~:text=to%20Apple%20Silicon-,On%20iOS%20there%20are%20no%20web%20browsers%20other%20than%20Safari,skins%20on%20top%20of%20Webkit.


Do you want me to add some info on this, and types to your Readme? (Because I mistakenly thought that 'download type' would actually be the format the audio is recorded into as well)

**Comment by samhirtarif** [comment]
Would be great if you could open up a separate discussion for this (would be closing this issue soon)
Also, please feel free to contribute 👍🏻

**Comment by samhirtarif** [comment]
> Because I mistakenly thought that 'download type' would actually be the format the audio is recorded into as well)

Also, no, as per my understanding, `mediaRecorder` only supports the type `webm` for recording.
Running `MediaRecorder.isTypeSupported("audio/aac")` on safari returns `false`. In fact, running `MediaRecorder.isTypeSupported("audio/webm")` returns `false` for safari too

**Comment by timhc22** [comment]
audio/mp4 seems to return true, thanks for that, that helped out a lot. Probably useful if I add to the readme, will open a pull request when I've done that
