### ISSUE TITLE
Could not find a declaration file for module 'react-audio-voice-recorder'. '

### ISSUE THREAD

**Issue by MubashirullahD** [samhirtarif/react-audio-recorder#76]
![image](https://github.com/samhirtarif/react-audio-recorder/assets/45071858/4117c5fb-8572-4fe5-a07c-521d7f6c4c4a)

> Could not find a declaration file for module 'react-audio-voice-recorder'. 'c:/Users/Mubashirullah/Documents/workspace/front/friction/node_modules/react-audio-voice-recorder/dist/react-audio-voice-recorder.es.js' implicitly has an 'any' type.
>   There are types at 'c:/Users/Mubashirullah/Documents/workspace/front/friction/node_modules/react-audio-voice-recorder/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'react-audio-voice-recorder' library may need to update its package.json or typing.

package.json:

```
{
  "name": "friction",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "lint": "eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0",
    "preview": "vite preview"
  },
  "dependencies": {
    "@chakra-ui/react": "^2.8.0",
    "@emotion/react": "^11.11.1",
    "@emotion/styled": "^11.11.0",
    "@hookform/resolvers": "^3.1.1",
    "@tremor/react": "^3.5.0",
    "axios": "^1.4.0",
    "framer-motion": "^10.13.1",
    "react": "^18.2.0",
    "react-audio-voice-recorder": "^2.1.2",
    "react-dom": "^18.2.0",
    "react-hook-form": "^7.45.2",
    "react-icons": "^4.10.1",
    "react-query": "^3.39.3",
    "react-router-dom": "^6.14.2",
    "validator": "^13.11.0",
    "xlsx": "https://cdn.sheetjs.com/xlsx-0.20.0/xlsx-0.20.0.tgz",
    "zod": "^3.21.4",
    "zustand": "^4.3.9"
  },
  "devDependencies": {
    "@types/node": "^20.4.5",
    "@types/react": "^18.2.15",
    "@types/react-dom": "^18.2.7",
    "@types/validator": "^13.9.0",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "@vitejs/plugin-react": "^4.0.3",
    "autoprefixer": "^10.4.14",
    "eslint": "^8.45.0",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-refresh": "^0.4.3",
    "postcss": "^8.4.27",
    "simple-zustand-devtools": "^1.1.0",
    "tailwindcss": "^3.3.3",
    "typescript": "^5.0.2",
    "vite": "^4.4.5"
  }
}

```

**Comment by samhirtarif** [comment]
Hey - I've never come across this issue before and it would be really hard to resolve just with the error message.
It would be really helpful if you could create a minimal reproduction of the issue for me to take a look at

**Comment by samhirtarif** [comment]
@MubashirullahD  - I've never come across this issue before and it would be really hard to resolve just with the error message.
It would be really helpful if you could create a minimal reproduction of the issue for me to take a look at

**Comment by samhirtarif** [comment]
My initial guess would be that something went wrong with the installation, and you could try uninstalling and re-installing the package

**Comment by MubashirullahD** [comment]
I retired the installation and it did not help.
I made a new project with my old dependencies and used the given example and it worked in the bare minimum state. Not sure what's wrong with the actual project.

**Comment by MubashirullahD** [comment]
If no one else has had this issue, I guess it might not be worthwhile spending time on. I'll use another library for my project. Thanks.

**Comment by samhirtarif** [comment]
I'm sorry that you had to face this issue :/
I'll still see if I can somehow figure it out

**Comment by MubashirullahD** [comment]
I found that saving the file as jsx stopped the error. But then I was mixing jsx and tsx and that needed to be addressed. [Possible solution for that](https://stackoverflow.com/questions/68321598/importing-jsx-in-tsx)
I however found the error doesn't stop the component from working so I used it.

**Comment by emigdio821** [comment]
I have the same issue using typescript (`.tsx`)
