### ISSUE TITLE
That's the annoying bug.

### ISSUE THREAD

**Issue by qq137321** [samhirtarif/react-audio-recorder#80]
Whenever I install react-audio-voice-recorder, my reactJS application fails to send messages correctly to the API. 
What's going on? It breaks as soon as I install it every time.

**Comment by samhirtarif** [comment]
Which API?
Is there any error that gets logged in the console or in the network requests?
Also, it would be helpful if you could create a minimal reproduction of the issue.

**Comment by samhirtarif** [comment]
I'm closing this till there are further details on this issue - Please feel free to re-open when you've added details.
