### ISSUE TITLE
Audio file doc_type webm

### ISSUE THREAD

**Issue by AwesomeZaidi** [samhirtarif/react-audio-recorder#85]
**Describe the bug**
Even after setting `downloadFileExtension="wav"` - the outputted audio file doc_type is still webm.

I see in the documentation that it is mentioned several times, my website must be cross-origin isolated and it gives links to a relatively vague Google article.

I am building a next js web app so in my `next.config.js` i made these changes in hopes to make my site cross-origin isolated, but i'm not sure if this is the right?

```
const nextConfig = {
  reactStrictMode: false,
  i18n,

  // Add headers for cross-origin isolation
  async headers() {
    return [
      {
        source: "/(.*)", // change to appropriate path
        headers: [
          {
            key: "Cross-Origin-Embedder-Policy-Report-Only",
            value: "require-corp",
          },
          {
            key: "Cross-Origin-Opener-Policy-Report-Only",
            value: "same-origin",
          },
        ],
      },
    ];
  },
};
```

**Expected behavior**
Can we provide documentation examples for how to cross-origin isolate a react or next js app? This is currently blocking my team from using this awesome package!

**Comment by AwesomeZaidi** [comment]
I did just test and i believe my site is now cross-origin isolated, i removed the ``Report-Only` from the above strings and now when i run new `SharedArrayBuffer(10);` in the chrome dev tools console, i get no error.

But even still, the doc_type of these audio files are webm files.

**Comment by samhirtarif** [comment]
@AwesomeZaidi - I am sorry to hear that you're having this trouble. It would be really helpful if you could create a repo with a minimal reproduction of this issue and I'll gladly take a look.

Without a reproduction, it would be really hard for me to debug this problem.

**Comment by samhirtarif** [comment]
I have spent some time trying to reproduce this on my end and have had no success thus far, with everything working as expected. I am closing this one for now.

Feel free to re-open it whenever you can share more info that can help with the reproduction of the issue you're facing
