### ISSUE TITLE
How can I set the downloadFileExtension when using the hook? 

### ISSUE THREAD

**Issue by GraysonNull** [samhirtarif/react-audio-recorder#86]
I'm using the `useAudioRecorder` hook so I can have a custom UI but I'm not finding any way to change the file extension. I'd like to have the recording be an mp3 but best I can tell it has to be a 'webm' when using the hook. Is there any way to change this?

**Comment by samhirtarif** [comment]
With the hook, you will have to implement the downloading yourself. However, you can pass the mimeType you want your recording to like so

```js
useAudioRecorder(
      null, //audioTrackConstraints
      null, //onNotAllowedOrFound
      { mimeType: "audio/webm" } // you can replace this with any other supported mimeType
);
```

BUT, that said, the "audio/mp3" mimeType is not supported either by Chrome or Firefox and you would need to find some way to convert `webm` to `mp3`. Which, in my experience and from what I've seen on the internet, is not an easy task

![image](https://github.com/samhirtarif/react-audio-recorder/assets/89391183/61412f76-821e-4dad-babc-90c9d9e54ee1)
Screenshot from Chrome

![image](https://github.com/samhirtarif/react-audio-recorder/assets/89391183/aef8b32e-1f1c-4bd3-8fb2-1848f7f9408f)
Screenshot from Mozilla

**Comment by GraysonNull** [comment]
Got it, this explains why I wasn't having success just changing the mimeType. I'll take a look into ffmpeg for converting it to mp3. Thank you!
