### ISSUE TITLE
Audio breaking in chrome android

### ISSUE THREAD

**Issue by prtkjakhar** [samhirtarif/react-audio-recorder#87]
**Describe the bug**
When trying to record audio on my android chrome (version 116.0.5845.163) the audio is very distorted and almost like the recorder is stopping and starting in between.

Attaching the example audio below recorded from [the stackblitz demo link](https://stackblitz.com/edit/react-ts-ryj6jz?file=App.tsx)
I am saying hello three to four times in the audio.

It's not happening on all people's browsers and my phone's microphone is working fine already tested that.

**Audio file**
[48787e2a-446c-4a88-a392-69d998550fdd.webm](https://github.com/samhirtarif/react-audio-recorder/assets/65057795/bbb90653-dafc-4eed-bcf5-2cc01deaa531)

**Comment by samhirtarif** [comment]
@prtkjakhar - I've tried this out on multiple android devices with version 116 and 117 but have not been able to re-produce this issue. I would have to mark this one closed for now since it's not reproducible.
